### ISSUE TITLE
onnx转rknn有问题

### ISSUE THREAD

**Issue by KaaiLee** [cqu20160901/yolov8n_onnx_tensorRT_rknn_horizon_dfl#6]
根据你的https://blog.csdn.net/zhangqian_1/article/details/135523096这个文档，在yolov8代码中添加相应的代码，导出onnx后，再用这个工具导出rknn，报错了
postprocess ...
(1, 80, 80, 80)
(1, 64, 80, 80)
(1, 80, 40, 40)
(1, 64, 40, 40)
(1, 80, 20, 20)
(1, 64, 20, 20)
Traceback (most recent call last):
  File "onnx2rknn_demo_ZQ.py", line 258, in <module>
    predbox = postprocess(out, img_h, img_w)
  File "onnx2rknn_demo_ZQ.py", line 138, in postprocess
    cls_val = cls[cl * mapSize[index][0] * mapSize[index][1] + h * mapSize[index][1] + w]
IndexError: index 409600 is out of bounds for axis 0 with size 409600

我对比了你导出的onnx模型，发现你是将激活函数都改成了relu，激活函数是必须要改的吗？

**Comment by KaaiLee** [comment]
还有就是我分别用了rknn-toolkit2的1.5.0和1.6.0版本去导出，都报这个错，不知道是哪一步有问题，能否指点以下呢

**Comment by KaaiLee** [comment]
已经看到已关闭的问题的回答，感谢
